### ISSUE TITLE
Infografía Librerías

### ISSUE THREAD

**Issue by AricelCastro** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-AricelCastro#1]
[INFOGRAFIA LIBRERIAS CASTRO RODRIGUEZ BETSABE ARICEL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-AricelCastro/files/14606141/INFOGRAFIA.LIBRERIAS.CASTRO.RODRIGUEZ.BETSABE.ARICEL.pdf)

**Comment by ElisabetRD** [comment]
18% faltan fuentes e información

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
